[package]
name = "secondbrain-markdown"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
markdown.workspace = true
secondbrain-core = { path = "../secondbrain-core" }
serde.workspace = true
serde_yaml.workspace = true

[dev-dependencies]
proptest.workspace = true
